name: DevFlow Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      template:
        description: "Template"
        required: true
        default: "nodejs"

      repo_url:
        description: "GitHub repo URL"
        required: true

      app_name:
        description: "App name"
        required: true

env:
  TEMPLATE: ${{ github.event.inputs.template }}
  REPO_URL: ${{ github.event.inputs.repo_url }}
  APP_NAME: ${{ github.event.inputs.app_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      # =========================
      # 🚀 NODE.JS DEPLOYMENT
      # =========================
      - name: Deploy Node App
        if: env.TEMPLATE == 'nodejs'
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

          cd ~
          rm -rf $APP_NAME

          git clone $REPO_URL $APP_NAME
          cd $APP_NAME

          source ~/.bashrc
          nvm use 16

          npm install

          pkill node || true

          if [ -f package.json ]; then
            nohup npm start > app.log 2>&1 &
          else
            nohup node index.js > app.log 2>&1 &
          fi

          sudo rm -f /etc/nginx/conf.d/app.conf

          echo "server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:3000;
              }
          }" | sudo tee /etc/nginx/conf.d/app.conf

          sudo systemctl restart nginx

          EOF

      # =========================
      # 🌐 STATIC DEPLOYMENT
      # =========================
      - name: Deploy Static Website
        if: env.TEMPLATE == 'static'
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

          cd ~
          rm -rf $APP_NAME

          git clone $REPO_URL $APP_NAME

          sudo rm -rf /usr/share/nginx/html/*

          sudo cp -r $APP_NAME/* /usr/share/nginx/html/

          sudo rm -f /etc/nginx/conf.d/app.conf

          sudo systemctl restart nginx

          EOF

      # =========================
      # ⚙️ WORKER DEPLOYMENT
      # =========================
      - name: Deploy Worker
        if: env.TEMPLATE == 'worker'
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

          cd ~
          rm -rf $APP_NAME

          git clone $REPO_URL $APP_NAME
          cd $APP_NAME

          pkill -f worker.js || true

          nohup node worker.js > worker.log 2>&1 &

          EOF